site_name: "VARS Query"
repo_url: https://github.com/mbari-org/vars-query-vue
repo_name: "vars-query-vue"
site_description: "VARS Query is a web application for querying and visualizing data from the VARS (Video Annotation and Reference System) database."
site_author: "MBARI"

nav:
  - <span style="color:#4488ed;">Home</span>: index.md
  - <span style="color:#4488ed;">Data Use</span>: 
    - Data Use Policy: data_use_policy.md
  - <span style="color:#4488ed;">Quickstart</span>: quickstart_search.md
    - Search by Concept: quickstart_search_concept.md
    - Search by Dive: quickstart_search_dive.md
  - <span style="color:#4488ed;">User Guide</span>: 
      - Introduction: doc_01_general_info.md
      - Getting Started: doc_getting_started.md
      - <span style="color:#4488ed;">Query Parameters</span>:
        - Concepts: doc_02_selecting_concept.md
        - Associations: doc_03_add_associations.md
        - Deployments and Camera Platforms: doc_04_add_deployments_cameraplatform.md
        - Location: doc_05_locations.md
        - Depth: doc_06_depth.md
        - Recorded Date: doc_07_recordeddate.md
        - Observation Date: doc_08_observation_date.md
        - Activities: doc_09_activities.md
        - Groups: doc_10_groups.md
        - Observers: doc_11_observers.md
        - Chief Scientists: doc_12_chief_scientists.md
        - Additional Data Returns: doc_13_additional_returns.md
        - Ancillary Data Returns: doc_14_ancillary_data_returns.md
      - <span style="color:#4488ed;">Query Results</span>:
        - Annotation Results: doc_15_annotation_results.md
  - <span style="color:#4488ed;">Appendix</span>: 
    - Knowledgebase Concepts: appendix_a.md
    - Knowledgebase Associations: appendix_b.md
  - MBARI Docs: "https://docs.mbari.org"
  

markdown_extensions:
  - meta
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true

plugins:
  - search
  - mermaid2
  - tags
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      width: 100%
      height: auto
      auto_themed: true
      auto_caption: true
theme:
  name: material
  logo: https://docs.mbari.org/imgs/mbari-logo.png
  palette:
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/brightness-auto
      name: System theme
  - scheme: slate
    media: "(prefers-color-scheme: dark)"
    primary: black
    toggle:
      icon: material/weather-night
      name: Dark mode
  - scheme: light
    media: "(prefers-color-scheme: light)"
    primary: blue grey
    toggle:
      icon: material/weather-sunny
      name: Light mode
  icon:
    repo: material/github
  features:
    - navigation.expand
    - navigation.instant
    - navigation.instant.progress
    - navigation.indexes
    - navigation.path
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tabs.sticky
    - navigation.tracking
    - toc.follow
    - toc.integrate
# extra_css:
#     - https://docs.mbari.org/css/mbari.css
#     - assets/css/extra.css


